### ISSUE TITLE
[Question] SN74AHCT125N level shifter

### ISSUE THREAD

**Issue by Noschvie** [zoesn89/WLED_PCB_D1_Mini#2]
Hello
why is this "SN74AHCT125N level shifter" needed ?
Thanks
Norbert

**Comment by f2daz** [comment]
Hey Norbert,

its needed, when you have a bigger distance between the ESP and the first LED. The ESP is working with 3,3V IO and the Strips often with 5V data signals. For short distances 3,3V is often enough, but on bigger distances the voltage drop is too big. So the level shifter puts the 3,3V signal to a 5V signal ;)

**Comment by Noschvie** [comment]
Hi Felix
do you have a list of the parts to be ordered online like conrad.at or reichelt.at ?
Thanks, Norbert

**Comment by Noschvie** [comment]
... Device is "up and running" , thanks again.

**Comment by f2daz** [comment]
> ... Device is "up and running" , thanks again.

Nice! Have fun with it 😉
P.S.: If you need an enclosure, I have a 3D printable one now :)

**Comment by Noschvie** [comment]
> P.S.: If you need an enclosure, I have a 3D printable one now :)

are these files accessible ? Thanks

**Comment by f2daz** [comment]
> are these files accessible ? Thanks

not yet, I'll upload them later ;)

**Comment by f2daz** [comment]
Hey,

I added the files ;) see https://github.com/zoesn89/WLED_PCB_D1_Mini/tree/main/Enclosure
