### ISSUE TITLE
Pin Belegung?

### ISSUE THREAD

**Issue by Webranger2** [zoesn89/WLED_PCB_D1_Mini#3]
Hi, erst mal danke für die super arbeit.
Ich hab direkt mal ein paar produzieren lassen.

Kannst du mir noch was zu der Pin Belegung bzw die Richtung wie ich den wemos und den Level shifter SN74AHCT125N einbauen muss sagen?

<img width="635" alt="Bildschirmfoto 2021-09-02 um 12 02 55" src="https://user-images.githubusercontent.com/44174579/131825968-55f40177-56cc-4245-bf78-b8b3b7fee481.png">

Gruss

**Comment by f2daz** [comment]
Hey @Webranger2,

schau dir mal den zweiten [Screenshot](https://github.com/zoesn89/WLED_PCB_D1_Mini/blob/main/WLED_Controller3.png) an, da sieht man, wie ich den WeMos platziert habe ;) 
Den SN74... steckst du so rein, wie auf der Platine abgedruckt. Sprich, mit Einkerbung nach oben.

Die Pinbelegung findest du jetzt [hier](https://github.com/zoesn89/WLED_PCB_D1_Mini/blob/main/WLED-Controller_sch.pdf).

**Comment by muesli** [comment]
I'm a bit confused as well. All the D1 Minis I got here seem to have a different pin-out than this PCB design. Can you share a photo of your D1?

Ja, ich bin genauso verwirrt. All die D1 Minis die ich hier hab scheinen eine andere Pin Belegung zu haben als dieses PCB Design. Könntest du ein Foto von deinem D1 posten?
