### ISSUE TITLE
Capacitor Voltage

### ISSUE THREAD

**Issue by mattgrooms** [zoesn89/WLED_PCB_D1_Mini#4]
Hi! I want to thank you for sharing this great project. This PCB is exactly what I have been wishing for! I just received PCBs and 3D printed enclosures from JLCPCB and I am impressed. What voltage rating do you suggest for C1? 6.3v, 10v, 12v? The voltage is not stated in the bill of materials (BOM), nor is it printed on the PCB silkscreen.

Danke

**Comment by f2daz** [comment]
Hi @mattgrooms,

thank you!😉  
I'm using a 10V capacitor, but 6,3V or 12V should be fine, too.

Best
Felix

**Comment by mattgrooms** [comment]
Thanks @zoesn89,

I will use 10v ones on the 25 boards I am building.
